"""Public M0-2A collection domain contract."""

from app.domain.collections.entities import (
    CollectionItem,
    CollectionKind,
    CollectionSource,
    Message,
    MessageContentType,
    MessageRole,
    Session,
    SessionChannel,
    SessionStatus,
    Source,
    SourceMetadata,
    SourceParseStatus,
    SourceType,
    SupportedCity,
    SupportedTimezone,
    User,
    UserMode,
)
from app.domain.collections.repositories import CollectionRepository, ResourceNotFoundError
from app.domain.collections.statuses import (
    DEFAULT_COLLECTION_STATUSES,
    PERSISTABLE_COLLECTION_STATUSES,
    PLAN_ELIGIBLE_COLLECTION_STATUSES,
    TERMINAL_COLLECTION_STATUSES,
    CollectionStatus,
    can_collection_enter_plan,
    ensure_collection_transition,
    ensure_persistable_collection_status,
    is_collection_visible_by_default,
)

__all__ = [
    "DEFAULT_COLLECTION_STATUSES",
    "PERSISTABLE_COLLECTION_STATUSES",
    "PLAN_ELIGIBLE_COLLECTION_STATUSES",
    "TERMINAL_COLLECTION_STATUSES",
    "CollectionItem",
    "CollectionKind",
    "CollectionRepository",
    "CollectionSource",
    "CollectionStatus",
    "Message",
    "MessageContentType",
    "MessageRole",
    "ResourceNotFoundError",
    "Session",
    "SessionChannel",
    "SessionStatus",
    "Source",
    "SourceMetadata",
    "SourceParseStatus",
    "SourceType",
    "SupportedCity",
    "SupportedTimezone",
    "User",
    "UserMode",
    "can_collection_enter_plan",
    "ensure_collection_transition",
    "ensure_persistable_collection_status",
    "is_collection_visible_by_default",
]
