"""Public M0-2A collection domain contract."""

from app.domain.collections.candidate_metadata import CandidateField, Uncertainty
from app.domain.collections.entities import (
    CollectionItem,
    CollectionSource,
    Message,
    MessageContentType,
    MessageRole,
    PlanCity,
    Session,
    SessionChannel,
    SessionStatus,
    Source,
    SourceMetadata,
    SourceParseStatus,
    SourceType,
    SupportedTimezone,
    User,
    UserMode,
)
from app.domain.collections.extraction import (
    MAX_EXTRACTION_CANDIDATES,
    EventCandidate,
    ExtractionCandidate,
    ExtractionOutcome,
    ExtractionReasonCode,
    ExtractionResult,
    PlaceCandidate,
    UnsupportedReason,
)
from app.domain.collections.repositories import (
    CollectionDataIntegrityError,
    CollectionRepository,
    ResourceNotFoundError,
)
from app.domain.collections.statuses import (
    DEFAULT_COLLECTION_STATUSES,
    DELETABLE_COLLECTION_STATUSES,
    PERSISTABLE_COLLECTION_STATUSES,
    PLAN_ELIGIBLE_COLLECTION_STATUSES,
    TERMINAL_COLLECTION_STATUSES,
    TERMINAL_RECOGNITION_STATUSES,
    CollectionStatus,
    CollectionWorkflowStatus,
    RecognitionStatus,
    can_collection_enter_plan,
    ensure_collection_transition,
    ensure_persistable_collection_status,
    is_collection_visible_by_default,
)
from app.domain.collections.types import CollectionKind
from app.domain.collections.writes import (
    AutoSaveResult,
    CollectionItemPatch,
    CollectionWriteOperation,
    IdempotencyConflictError,
    UndoOutcome,
    UndoResult,
    VersionConflictError,
    status_for_extraction_candidate,
)

__all__ = [
    "DEFAULT_COLLECTION_STATUSES",
    "DELETABLE_COLLECTION_STATUSES",
    "PERSISTABLE_COLLECTION_STATUSES",
    "PLAN_ELIGIBLE_COLLECTION_STATUSES",
    "TERMINAL_COLLECTION_STATUSES",
    "TERMINAL_RECOGNITION_STATUSES",
    "MAX_EXTRACTION_CANDIDATES",
    "CandidateField",
    "AutoSaveResult",
    "CollectionItem",
    "CollectionItemPatch",
    "CollectionDataIntegrityError",
    "CollectionKind",
    "CollectionRepository",
    "CollectionSource",
    "CollectionStatus",
    "CollectionWorkflowStatus",
    "CollectionWriteOperation",
    "EventCandidate",
    "ExtractionCandidate",
    "ExtractionOutcome",
    "ExtractionReasonCode",
    "ExtractionResult",
    "IdempotencyConflictError",
    "Message",
    "MessageContentType",
    "MessageRole",
    "PlanCity",
    "PlaceCandidate",
    "ResourceNotFoundError",
    "RecognitionStatus",
    "Session",
    "SessionChannel",
    "SessionStatus",
    "Source",
    "SourceMetadata",
    "SourceParseStatus",
    "SourceType",
    "SupportedTimezone",
    "User",
    "UserMode",
    "Uncertainty",
    "UnsupportedReason",
    "UndoOutcome",
    "UndoResult",
    "VersionConflictError",
    "can_collection_enter_plan",
    "ensure_collection_transition",
    "ensure_persistable_collection_status",
    "is_collection_visible_by_default",
    "status_for_extraction_candidate",
]
